# Example on how to run this setup in docker-compose

version: "2"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.build
        environment:
            VERSION: dev
        volumes:
            - "$HOME/.m2:/root/.m2"
        ports:
            - "8080:8080"
        command: bash -c 'make && java -jar target/spring-boot-app-dev.jar'
